using System.Globalization;
using System.Windows.Media;
using Counter.Core.Colour;
using Counter.Core.Models;

namespace Counter.App.Theme;

/// <summary>
/// The five stops of one illuminated gradient, in the order they are painted.
///
/// Five rather than three because three cannot describe light. A three-stop ramp reads as a
/// blend between two colours with something in the middle; five gives the lit edge somewhere to
/// go before the material's own colour arrives, and gives the shadowed half room to deepen
/// without the middle looking washed out. The offsets are fixed for every gradient in the
/// application - 0, 18, 48, 76 and 100 percent - so two gradients side by side are lit the same
/// way even when they are different colours.
/// </summary>
/// <param name="Highlight">0 percent. Where the light meets the material, at the upper left.</param>
/// <param name="Light">18 percent. Still lit, but the colour is readable in it.</param>
/// <param name="Base">48 percent. The true colour of the family.</param>
/// <param name="Strong">76 percent. Turning away from the light.</param>
/// <param name="Deep">100 percent. The shadowed edge, at the lower right.</param>
public readonly record struct GradientRamp(
    string Highlight, string Light, string Base, string Strong, string Deep)
{
    /// <summary>Builds the ramp for one accent, straight off the engine.</summary>
    public static GradientRamp From(AccentRamp ramp) =>
        new(ramp.Highlight, ramp.Light, ramp.Base, ramp.Strong, ramp.Deep);

    /// <summary>Builds the ramp for a semantic state from its one defining colour.</summary>
    public static GradientRamp FromBase(string colour) => From(AccentEngine.Derive(colour));

    /// <summary>The five stops in painting order, so a brush builder does not repeat itself.</summary>
    public IReadOnlyList<string> Stops => new[] { Highlight, Light, Base, Strong, Deep };
}

/// <summary>
/// Every colour in the application, assembled from three independent inputs.
///
/// 1. <b>Neutral</b> - the glass, the ink and the structural contours that make up almost all of
///    the interface. Two hand-tuned sets, one per theme, carrying exactly the same keys. A key
///    present in one and missing in the other is a control that goes black in light mode or
///    invisible in dark mode, which is the single most common way a second theme rots, so a test
///    asserts the sets are identical and the failure lands on a build rather than on somebody's
///    screen.
///
/// 2. <b>Accent</b> - everything that follows the colour the user picked. Not listed: generated,
///    stop by stop, by <see cref="AccentEngine"/> from that one colour. There is no orange branch
///    and no blue branch. Choosing Orange cannot leave a blue focus ring behind in some corner
///    nobody looked at, because nothing anywhere names a colour.
///
/// 3. <b>Semantic</b> - paused, warning, error and completed. Fixed families that do not follow
///    the accent, because a paused timer that turns pink when the accent is pink has stopped
///    carrying information. They are generated by the same engine from their own base colours,
///    so a red ramp is lit exactly the way an accent ramp is; only the hue is fixed.
///
/// The solid map is what <see cref="ThemeService"/> pushes into the resource dictionary. The
/// gradient map is separate because gradients are built as brushes with stops rather than parsed
/// from a string, and because the rule about where a gradient may appear is worth being able to
/// state in one place: an active control, a status indicator, and nothing else.
/// </summary>
public static class ThemePalette
{
    /// <summary>The colour of the drop shadows, which are effects and so take a colour.</summary>
    public const string ShadowKey = "ShadowColor";

    // ==================================================================== neutral

    /// <summary>
    /// Dark glass.
    ///
    /// Not black, and not opaque. The surfaces carry an alpha channel because the panel is meant
    /// to read as smoked glass laid over the desktop rather than as a black card sitting on it:
    /// what is underneath stays faintly present, which is what gives the material any depth at all.
    ///
    /// The alphas are set for the simulated fallback rather than for a compositor backdrop, and
    /// that is a real difference. A blurred backdrop destroys the detail behind the glass, so it
    /// can afford to be eighty percent opaque and still be perfectly readable. This window cannot
    /// have one - see BackdropService - so what shows through is the desktop at full sharpness,
    /// and at eighty percent a line of text underneath the panel is not a suggestion of depth, it
    /// is a line of text you can read. The assembled panel therefore lands near ninety percent:
    /// enough that the desktop is a tone rather than content, little enough that the surface still
    /// moves with what is behind it.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>
    {
        // Glass. The surfaces the whole interface is built from.
        ["GlassBaseBrush"] = "#DE181C23",
        ["GlassRaisedBrush"] = "#E61D222B",
        ["GlassDeepBrush"] = "#EA101318",
        ["GlassHoverBrush"] = "#E0252C37",
        ["GlassTintBrush"] = "#241D222B",
        ["GlassInnerLightBrush"] = "#18FFFFFF",
        ["GlassInnerShadowBrush"] = "#18000000",

        // The soft white light held inside the edge, and the one that spills outward. Both are
        // plain white with an alpha: the blur that turns them into a glow lives in the template,
        // because a colour cannot describe a radius. Solid glass has neither.
        ["GlassRimBrush"] = "#00FFFFFF",
        ["GlassHaloBrush"] = "#00FFFFFF",

        // A task row is a raised sheet of the same glass rather than a card of its own, so it is
        // a thin wash over whatever the panel is showing rather than another opaque surface.
        ["RowGlassBrush"] = "#14FFFFFF",
        ["RowGlassHoverBrush"] = "#26FFFFFF",
        ["RowContourBrush"] = "#14FFFFFF",

        // Opaque equivalents, for the few places a surface genuinely must not show through: a
        // popover laid over the panel's own content, and the ground behind a text field.
        ["BackgroundBrush"] = "#FF0E1116",
        ["NotchBackgroundBrush"] = "#FF141820",
        ["SurfaceBrush"] = "#FF1A202A",
        ["SurfaceRaisedBrush"] = "#FF202735",
        ["SurfaceHoverBrush"] = "#FF202735",
        ["SurfacePressedBrush"] = "#FF252E3C",
        ["TransparentBrush"] = "#00000000",

        ["BorderSubtleBrush"] = "#FF2A3340",
        ["BorderVisibleBrush"] = "#FF354152",

        ["TextPrimaryBrush"] = "#FFF4F7FA",
        // The quiet end of the ladder, solved for the surface it actually stands on rather
        // than for a solid one. Even the densest glass here is translucent: a white wallpaper
        // lifts the dark panel from near-black to a mid grey, and a muted tone chosen against
        // near-black disappears at that point. See Ink and docs/DESIGN.md.
        ["TextSecondaryBrush"] = "#FFB7C1CE",
        ["TextMutedBrush"] = "#FF939EAD",
        ["TextDisabledBrush"] = "#FF6B7683",
        ["TextOnAccentBrush"] = "#FFFFFFFF",

        ["EdgeIdleBrush"] = "#FF354152",
        ["EdgeExpandedBrush"] = "#FF354152",
        ["EdgeHoverBrush"] = "#FF44526A",
        ["EdgePanelBrush"] = "#FF2A3340",

        // The recessed track the progress light runs in. Cut into the glass rather than painted
        // on it, which is why it is white at low alpha rather than a surface colour.
        ["ProgressTrackBrush"] = "#20FFFFFF",

        ["HeatBrush0"] = "#FF232A34",
        ["ChartGridBrush"] = "#FF2A3340",
        ["ChartEmptyBrush"] = "#FF232A34",
        ["ScrollThumbBrush"] = "#FF3B4655",

        // Effects take a colour, not a brush.
        [ShadowKey] = "#FF000000"
    };

    /// <summary>
    /// Light glass. Higher alpha than the dark set, because white glass over a bright wallpaper
    /// has almost no tonal separation to work with and text is the first thing to suffer.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>
    {
        ["GlassBaseBrush"] = "#E6FFFFFF",
        ["GlassRaisedBrush"] = "#F2FFFFFF",
        ["GlassDeepBrush"] = "#E8F3F6FA",
        ["GlassHoverBrush"] = "#F2F8FAFC",
        ["GlassTintBrush"] = "#1AFFFFFF",
        ["GlassInnerLightBrush"] = "#70FFFFFF",
        ["GlassInnerShadowBrush"] = "#12000000",

        ["GlassRimBrush"] = "#00FFFFFF",
        ["GlassHaloBrush"] = "#00FFFFFF",

        ["RowGlassBrush"] = "#8AFFFFFF",
        ["RowGlassHoverBrush"] = "#C4FFFFFF",
        ["RowContourBrush"] = "#1A000000",

        ["BackgroundBrush"] = "#FFF1F4F8",
        ["NotchBackgroundBrush"] = "#FFFFFFFF",
        ["SurfaceBrush"] = "#FFF7F9FC",
        ["SurfaceRaisedBrush"] = "#FFEEF2F7",
        ["SurfaceHoverBrush"] = "#FFEEF2F7",
        ["SurfacePressedBrush"] = "#FFE5EAF1",
        ["TransparentBrush"] = "#00000000",

        ["BorderSubtleBrush"] = "#FFD8E0E9",
        ["BorderVisibleBrush"] = "#FFC7D1DD",

        ["TextPrimaryBrush"] = "#FF11151C",
        // As in the dark set, and for the same reason: a black wallpaper drags the light
        // panel down to a mid grey, and the muted tone has to clear it there.
        ["TextSecondaryBrush"] = "#FF4E5A6B",
        ["TextMutedBrush"] = "#FF6F7987",
        ["TextDisabledBrush"] = "#FF99A3B0",
        ["TextOnAccentBrush"] = "#FFFFFFFF",

        // The outer edge has to stay visible against a white wallpaper, so light mode uses the
        // stronger border tone where dark mode can get away with the subtle one.
        ["EdgeIdleBrush"] = "#FFC7D1DD",
        ["EdgeExpandedBrush"] = "#FFC7D1DD",
        ["EdgeHoverBrush"] = "#FFAEBBCB",
        ["EdgePanelBrush"] = "#FFC7D1DD",

        ["ProgressTrackBrush"] = "#18000000",

        ["HeatBrush0"] = "#FFE3E8EF",
        ["ChartGridBrush"] = "#FFD8E0E9",
        ["ChartEmptyBrush"] = "#FFE3E8EF",
        ["ScrollThumbBrush"] = "#FFB4BDC9",

        // A soft neutral shadow rather than black, which on a light ground reads as dirt.
        [ShadowKey] = "#FF64748B"
    };

    // ==================================================================== semantic families

    /// <summary>Amber. A held session, and nothing else.</summary>
    public const string PausedBase = "#FFF3B643";

    /// <summary>Warm yellow-orange. Something needs attention but nothing has gone wrong.</summary>
    public const string WarningBase = "#FFE6AA4F";

    /// <summary>Red. Errors and destructive actions. Never used to mean "urgent and fine".</summary>
    public const string DangerBase = "#FFEF6472";

    /// <summary>Green. Work that finished.</summary>
    public const string SuccessBase = "#FF39C781";

    public static GradientRamp Paused => GradientRamp.FromBase(PausedBase);

    public static GradientRamp Warning => GradientRamp.FromBase(WarningBase);

    public static GradientRamp Danger => GradientRamp.FromBase(DangerBase);

    public static GradientRamp Success => GradientRamp.FromBase(SuccessBase);

    // ==================================================================== materials

    /// <summary>
    /// What each glass is made of, as the difference from the theme's own neutral set.
    ///
    /// Only the keys that actually change are listed. Writing complete dictionaries per material
    /// would mean several places to forget an ink colour, and the whole point of the neutral set
    /// is that it is one place.
    ///
    /// <para>
    /// The density depends on whether there is a real blur behind the panel, and it has to. A
    /// frosted card on a web page can sit at eighteen percent because <c>backdrop-filter</c> has
    /// already destroyed the detail behind it before the tint arrives; the tint is only tinting a
    /// wash. Take the blur away and the same alpha leaves a browser with readable text in it
    /// sitting under the timer. So there are two tables: one for a panel with acrylic underneath
    /// it, which is close to the reference, and one for a panel with the bare desktop underneath,
    /// which is as thin as legibility allows and no thinner.
    /// </para>
    /// </summary>
    public static IReadOnlyDictionary<string, string> GlassOverrides(
        bool isLight, GlassMaterial material, bool blurred = false)
    {
        if (material == GlassMaterial.Solid)
        {
            return new Dictionary<string, string>();
        }

        var frosted = material == GlassMaterial.Frosted;

        // body, raised, deep, hover: the four glass densities, in the order the surfaces stack.
        var alphas = (frosted, blurred, isLight) switch
        {
            // Frosted over acrylic. Thinner than it is without one, because the acrylic is
            // already carrying a tint of its own - but not as thin as the reference designs,
            // and for a measured reason. A blur destroys detail; it does not change luminance.
            // A white wallpaper blurred is still white, and text on a surface that is mostly
            // white wallpaper is text nobody can read.
            (true, true, true) => new byte[] { 0x73, 0x80, 0x80, 0x92 },
            (true, true, false) => new byte[] { 0x86, 0x93, 0x93, 0xA4 },

            // Frosted over the bare desktop. Denser than it would like to be, because with
            // nothing blurring behind it the tint is the only thing standing between the user
            // and their own browser, and a panel you can read through is not frosted glass, it
            // is a window.
            (true, false, true) => new byte[] { 0xD4, 0xDE, 0xDE, 0xE6 },
            (true, false, false) => new byte[] { 0xCE, 0xD8, 0xD8, 0xDA },

            // Liquid over acrylic: the thinnest sheet in the application, and the one that
            // had to give the most ground. It is still the material you can see the most
            // through, which is the idea of it; it is no longer one you can read a browser
            // through, which was never the idea of it.
            (false, true, true) => new byte[] { 0x42, 0x4E, 0x4E, 0x60 },
            (false, true, false) => new byte[] { 0x40, 0x4C, 0x4C, 0x5C },

            // Liquid over the bare desktop. Still the thinnest of the three, but the gap
            // between it and frosted is now carried by the edge rather than by transparency.
            (false, false, true) => new byte[] { 0xC2, 0xCE, 0xCE, 0xD8 },
            _ => new byte[] { 0xBC, 0xC8, 0xC8, 0xD2 }
        };

        var body = isLight
            ? new[] { "FFFFFF", "FFFFFF", "F5F8FC", "FFFFFF" }
            : new[] { "16191F", "1A1E26", "0E1116", "232935" };

        string Glass(int index) =>
            "#" + alphas[index].ToString("X2", CultureInfo.InvariantCulture) + body[index];

        var map = new Dictionary<string, string>
        {
            ["GlassBaseBrush"] = Glass(0),
            ["GlassRaisedBrush"] = Glass(1),
            ["GlassDeepBrush"] = Glass(2),
            ["GlassHoverBrush"] = Glass(3),

            // A pale wash over the body rather than instead of it: the reference's near-white
            // fill is the whole surface on a light page, and here it is the part of the surface
            // that catches the light. Liquid glass tints nothing at all, exactly as written.
            // The pale wash frosted glass carries. Lighter in the dark theme than the
            // reference asks for, because a white wash on a dark panel is the one layer that
            // works directly against the ink standing on it: every point of it is a point of
            // contrast taken from text that had none to spare.
            ["GlassTintBrush"] = frosted
                ? (isLight ? "#2EFAFAFA" : "#12FAFAFA")
                : "#00FFFFFF",

            ["RowGlassBrush"] = isLight ? (frosted ? "#5CFFFFFF" : "#4AFFFFFF") : (frosted ? "#12FFFFFF" : "#0EFFFFFF"),
            ["RowGlassHoverBrush"] = isLight ? (frosted ? "#94FFFFFF" : "#80FFFFFF") : (frosted ? "#24FFFFFF" : "#1FFFFFFF"),

            // Frosted: the reference's inset 0 0 4px 2px rgba(255,255,255,0.45).
            // Liquid: its inset 0 0 12px -4px at 0.7, and the outward 0 0 21px -8px at 0.3.
            ["GlassRimBrush"] = frosted ? "#73FFFFFF" : "#B3FFFFFF",
            ["GlassHaloBrush"] = frosted ? "#00FFFFFF" : "#4DFFFFFF"
        };

        foreach (var (key, value) in Ink(material, isLight))
        {
            map[key] = value;
        }

        return map;
    }

    /// <summary>
    /// The quiet end of the ink ladder, per material.
    ///
    /// Quieter ink over a translucent panel is not quiet, it is gone. The contrast a muted tone
    /// was measured against was a solid surface, and there is no solid surface here: the panel
    /// shows whatever is behind it, and what is behind it is a wallpaper nobody chose for its
    /// legibility. So each step moves back toward the primary ink by roughly what the surface
    /// gives away, and the thinner the material the further it moves.
    ///
    /// The numbers are not taste. They come from photographing the real window over a field of
    /// saturated bands - pure white and pure black among them - measuring the worst surface
    /// luminance each material actually produces, and solving for the ink that clears 4.5:1 for
    /// text and 3:1 for the muted tone at that luminance. See docs/DESIGN.md.
    /// </summary>
    private static Dictionary<string, string> Ink(GlassMaterial material, bool isLight)
    {
        var ink = (material, isLight) switch
        {
            // Frosted: a pale wash over the blur, which costs the dark theme more than the
            // light one because the wash and the ink are pulling the same direction there.
            (GlassMaterial.Frosted, true) => new[] { "#FF44505F", "#FF6B7788", "#FF9AA5B2" },
            (GlassMaterial.Frosted, false) => new[] { "#FFD2DAE6", "#FFADB7C5", "#FF7B8694" },

            // Liquid: the thinnest, so the ladder is the most compressed.
            (_, true) => new[] { "#FF35404E", "#FF57626F", "#FF8B96A3" },
            _ => new[] { "#FFDEE5EC", "#FFB2BCC9", "#FF868F9C" }
        };

        return new Dictionary<string, string>
        {
            ["TextSecondaryBrush"] = ink[0],
            ["TextMutedBrush"] = ink[1],
            ["TextDisabledBrush"] = ink[2]
        };
    }

    // ==================================================================== assembly

    /// <summary>Every solid colour for one theme, one accent and one glass, keyed by resource name.</summary>
    public static IReadOnlyDictionary<string, string> Solids(
        bool isLight,
        AccentPalette accent,
        GlassMaterial material = GlassMaterials.Default,
        bool blurred = false)
    {
        var map = new Dictionary<string, string>(isLight ? Light : Dark);

        foreach (var (key, value) in GlassOverrides(isLight, material, blurred))
        {
            map[key] = value;
        }

        foreach (var (key, value) in AccentColours(accent, isLight))
        {
            map[key] = value;
        }

        foreach (var (key, value) in SemanticColours(isLight))
        {
            map[key] = value;
        }

        return map;
    }

    /// <summary>Every gradient, keyed by resource name. All five-stop, all one family each.</summary>
    public static IReadOnlyDictionary<string, GradientRamp> Gradients(AccentPalette accent)
    {
        var ramp = Ramp(accent);

        return new Dictionary<string, GradientRamp>
        {
            // Ongoing work wears the colour the user chose. Three keys rather than one, because
            // the fill, the contour and the running state are separable ideas even when they
            // happen to resolve to the same ramp.
            ["AccentGradientBrush"] = ramp,
            ["AccentContourBrush"] = ramp,
            ["RunningGradientBrush"] = ramp,

            // The state ramps do not, so a held timer stays amber and a failure stays red
            // whatever colour the user likes.
            ["PausedGradientBrush"] = Paused,
            ["WarningGradientBrush"] = Warning,
            ["DangerGradientBrush"] = Danger,
            ["SuccessGradientBrush"] = Success
        };
    }

    /// <summary>The five stops of the chosen accent, in gradient order.</summary>
    public static GradientRamp Ramp(AccentPalette accent) => GradientRamp.From(accent.Ramp);

    // ==================================================================== accent

    /// <summary>
    /// Everything the accent drives, derived rather than listed.
    ///
    /// The seven ramp stops come straight from the engine. The rest is arithmetic on them: a
    /// hover tone is the ink moved a third of the way toward the lit stop, a pressed tone a third
    /// toward the shadowed one, and the heat ramp is the ink mixed into the empty-cell surface in
    /// four even steps. Written out by hand, six palettes times two themes would be several
    /// hundred values to keep in step, and a custom colour could not exist at all.
    /// </summary>
    private static Dictionary<string, string> AccentColours(AccentPalette accent, bool isLight)
    {
        var ramp = accent.Ramp;

        var highlight = ToColor(ramp.Highlight);
        var light = ToColor(ramp.Light);
        var mid = ToColor(ramp.Base);
        var strong = ToColor(ramp.Strong);
        var deep = ToColor(ramp.Deep);
        var shadow = ToColor(ramp.Shadow);
        var glow = ToColor(ramp.Glow);

        // Which end of the ramp reads as "the accent" depends on what it is drawn against. On a
        // dark surface the base is the right weight; on white it is too pale to be legible as
        // text or as a hairline, so the light theme takes the strong stop.
        var ink = isLight ? strong : mid;
        var surface = ToColor(isLight ? Light["HeatBrush0"] : Dark["HeatBrush0"]);

        return new Dictionary<string, string>
        {
            // The seven generated stops, for anything that builds its own thing from them.
            ["AccentHighlightBrush"] = Hex(highlight),
            ["AccentLightBrush"] = Hex(light),
            ["AccentBaseBrush"] = Hex(mid),
            ["AccentStrongBrush"] = Hex(strong),
            ["AccentDeepBrush"] = Hex(deep),
            ["AccentShadowBrush"] = Hex(shadow),
            ["AccentGlowBrush"] = Hex(glow),
            ["AccentForegroundBrush"] = ramp.Foreground,
            ["AccentGlyphBrush"] = ramp.Glyph,

            // Solid accent, for text, icons and hairlines.
            ["AccentBrush"] = Hex(ink),
            ["AccentHoverBrush"] = Hex(Mix(ink, light, 0.35)),
            ["AccentPressedBrush"] = Hex(Mix(ink, deep, 0.35)),

            // A wash behind a selected icon button, and the warm light the glass picks up close
            // to an active control. Low enough to read as a tint on the surface rather than as a
            // second control, and never applied behind an inactive row.
            ["AccentSoftBrush"] = Hex(WithAlpha(mid, isLight ? (byte)0x22 : (byte)0x2E)),
            ["AccentSoftTintBrush"] = Hex(WithAlpha(mid, isLight ? (byte)0x12 : (byte)0x16)),

            ["PrimaryFillBrush"] = Hex(ink),
            ["PrimaryFillHoverBrush"] = Hex(Mix(ink, light, 0.35)),
            ["PrimaryFillPressedBrush"] = Hex(Mix(ink, deep, 0.35)),
            ["SelectionFillBrush"] = Hex(ink),

            ["EdgeRunningBrush"] = Hex(ink),
            ["EdgeNotchRunningBrush"] = Hex(ink),
            ["ProgressRunningBrush"] = Hex(ink),

            ["FocusRingBrush"] = Hex(ink),
            ["RowFocusedBorderBrush"] = Hex(Mix(surface, ink, isLight ? 0.45 : 0.55)),
            ["NotchGlowBrush"] = Hex(glow),

            ["ChartBarBrush"] = Hex(ink),
            ["ChartBarManualBrush"] = Hex(Mix(surface, ink, 0.55)),

            // Four steps from the empty-cell surface to the accent. Evenly spaced so the ramp
            // reads as intensity rather than as four unrelated colours.
            ["HeatBrush1"] = Hex(Mix(surface, ink, 0.30)),
            ["HeatBrush2"] = Hex(Mix(surface, ink, 0.55)),
            ["HeatBrush3"] = Hex(Mix(surface, ink, 0.80)),
            ["HeatBrush4"] = Hex(ink),
            ["HeatTodayRingBrush"] = isLight ? Light["TextSecondaryBrush"] : "#FF8FA3BC"
        };
    }

    // ==================================================================== semantic

    private static Dictionary<string, string> SemanticColours(bool isLight)
    {
        // The strong stop on white, the base stop on a dark surface. Same family either way, so
        // the meaning of the colour never moves even though its tone does.
        string Tone(GradientRamp ramp) => isLight ? ramp.Strong : ramp.Base;

        var danger = ToColor(Tone(Danger));
        var success = ToColor(Tone(Success));

        return new Dictionary<string, string>
        {
            ["PausedBrush"] = Tone(Paused),
            ["WarningBrush"] = Tone(Warning),
            ["DangerBrush"] = Tone(Danger),
            ["SuccessBrush"] = Tone(Success),

            ["EdgePausedBrush"] = Tone(Paused),
            ["EdgeUrgentBrush"] = Tone(Danger),
            ["EdgeCompletedBrush"] = Tone(Success),

            ["ProgressPausedBrush"] = Tone(Paused),
            ["ProgressUrgentBrush"] = Tone(Danger),
            ["ProgressCompletedBrush"] = Tone(Success),

            // A finished task takes the completion family rather than the accent - the wash
            // behind the row, the control that was ticked, and the ink inside it. Completion is a
            // meaning, not a preference: it cannot follow the colour somebody chose, or a green
            // accent would make every open task look done. The checkmark and the struck-through
            // title carry it whether or not anybody can see the colour at all.
            ["SuccessSoftBrush"] = Hex(WithAlpha(success, isLight ? (byte)0x1A : (byte)0x18)),
            ["SuccessGlyphBrush"] = AccentEngine.Glyph(Success.Base, Success.Strong),

            // Destructive controls are neutral until hovered, so none of these is ever the
            // resting state of a delete button.
            ["DestructiveHoverBrush"] = Hex(WithAlpha(danger, isLight ? (byte)0x22 : (byte)0x33)),
            ["DestructivePressedBrush"] = Hex(WithAlpha(danger, isLight ? (byte)0x33 : (byte)0x4D)),
            ["DestructiveBorderBrush"] = isLight ? "#FFF0C2C8" : "#FF5A3038",
            ["ErrorSurfaceBrush"] = isLight ? "#FFFDF2F3" : "#FF241A1E",
            ["ErrorBorderBrush"] = isLight ? "#FFF0C2C8" : "#FF5A3038"
        };
    }

    // ==================================================================== colour arithmetic

    public static Color ToColor(string value) =>
        (Color)ColorConverter.ConvertFromString(value)!;

    private static string Hex(Color colour) => string.Format(
        CultureInfo.InvariantCulture, "#{0:X2}{1:X2}{2:X2}{3:X2}",
        colour.A, colour.R, colour.G, colour.B);

    /// <summary>Linear blend. <paramref name="amount"/> of 1 returns <paramref name="b"/>.</summary>
    private static Color Mix(Color a, Color b, double amount)
    {
        byte Channel(byte x, byte y) => (byte)Math.Round(x + ((y - x) * amount), MidpointRounding.AwayFromZero);

        return Color.FromArgb(
            Channel(a.A, b.A), Channel(a.R, b.R), Channel(a.G, b.G), Channel(a.B, b.B));
    }

    private static Color WithAlpha(Color colour, byte alpha) =>
        Color.FromArgb(alpha, colour.R, colour.G, colour.B);

    // ==================================================================== preferences

    /// <summary>Resolves what a theme preference actually means right now.</summary>
    public static IReadOnlyDictionary<string, string> For(
        ThemePreference preference,
        bool systemIsLight,
        AccentPalette accent,
        GlassMaterial material = GlassMaterials.Default) =>
        Solids(IsLight(preference, systemIsLight), accent, material);

    public static bool IsLight(ThemePreference preference, bool systemIsLight) => preference switch
    {
        ThemePreference.Light => true,
        ThemePreference.Dark => false,
        _ => systemIsLight
    };

    public static string Label(ThemePreference preference) => preference switch
    {
        ThemePreference.Light => "Light",
        ThemePreference.Dark => "Dark",
        _ => "System"
    };

    public static ThemePreference Parse(string? value) => value?.Trim().ToLowerInvariant() switch
    {
        "light" => ThemePreference.Light,
        "dark" => ThemePreference.Dark,
        _ => ThemePreference.System
    };
}
