using System.Globalization;
using System.Windows;
using System.Windows.Data;
using System.Windows.Media;
using Counter.App.Theme;

namespace Counter.App.Converters;

public sealed class InverseBooleanConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        => value is bool b && !b;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        => value is bool b && !b;
}

public sealed class InverseBooleanToVisibilityConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        => value is bool b && b ? Visibility.Collapsed : Visibility.Visible;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        => value is Visibility v && v != Visibility.Visible;
}

/// <summary>Renders the 2px focus progress line: fraction remaining times the track width.</summary>
public sealed class ProgressWidthConverter : IMultiValueConverter
{
    public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
    {
        if (values.Length < 2
            || values[0] is not double fraction
            || values[1] is not double trackWidth
            || double.IsNaN(trackWidth)
            || trackWidth <= 0)
        {
            return 0d;
        }

        return Math.Clamp(fraction, 0d, 1d) * trackWidth;
    }

    public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
        => throw new NotSupportedException();
}

/// <summary>A percentage of a measured track width, for the top-task proportion bars.</summary>
public sealed class PercentWidthConverter : IMultiValueConverter
{
    public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
    {
        if (values.Length < 2
            || values[0] is not double percent
            || values[1] is not double trackWidth
            || double.IsNaN(trackWidth)
            || trackWidth <= 0)
        {
            return 0d;
        }

        return Math.Clamp(percent, 0d, 100d) / 100d * trackWidth;
    }

    public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
        => throw new NotSupportedException();
}

/// <summary>True when a string has content. Used to show optional secondary lines.</summary>
public sealed class StringNotEmptyToVisibilityConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        => string.IsNullOrWhiteSpace(value as string) ? Visibility.Collapsed : Visibility.Visible;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        => throw new NotSupportedException();
}

/// <summary>
/// Builds one accent swatch's gradient from the palette's single base colour.
///
/// The swatch has to paint the real gradient rather than a flat approximation of it: the whole
/// point of the picker is that the colour you press is the colour the interface takes, and a
/// solid dot beside a lit gradient is a different colour. It is generated by the same engine and
/// built by the same brush code the theme uses, from the same one input, so a swatch cannot drift
/// from what selecting it produces.
/// </summary>
public sealed class AccentSwatchBrushConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is not string colour || colour.Length == 0)
        {
            return DependencyProperty.UnsetValue;
        }

        return ThemeService.BuildGradient(GradientRamp.FromBase(colour));
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) =>
        throw new NotSupportedException();
}

/// <summary>
/// Shrinks a corner radius by the thickness of the contour drawn around it.
///
/// A rounded border with a one-pixel ring around it needs the inner shape to be one pixel
/// tighter, or the two curves are not concentric and the corner shows a sliver of the outer
/// colour on the inside of the bend. It is a single pixel, and it is the difference between a
/// contour that looks machined and one that looks approximate.
/// </summary>
public sealed class InsetCornerRadiusConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is not CornerRadius radius)
        {
            return DependencyProperty.UnsetValue;
        }

        var inset = parameter switch
        {
            double given => given,
            string text when double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) => parsed,
            _ => 1.0
        };

        static double Tighten(double corner, double by) => Math.Max(0, corner - by);

        return new CornerRadius(
            Tighten(radius.TopLeft, inset),
            Tighten(radius.TopRight, inset),
            Tighten(radius.BottomRight, inset),
            Tighten(radius.BottomLeft, inset));
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) =>
        throw new NotSupportedException();
}
